// <auto-generated />
namespace Shopping.Repository.Write.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class jksdfg1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jksdfg1));
        
        string IMigrationMetadata.Id
        {
            get { return "201811280930272_jksdfg1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
